dit_dashboard:
    resource: "@AdminBundle/Resources/config/routing/dashboard.yml"
    prefix:   /

dit_role:
    resource: "@AdminBundle/Resources/config/routing/role.yml"
    prefix:   /role

dit_email_newsletter:
    resource: "@AdminBundle/Resources/config/routing/email_newsletter.yml"
    prefix:   /email-newsletter

dit_message_newsletter:
    resource: "@AdminBundle/Resources/config/routing/message_newsletter.yml"
    prefix:   /message-newsletter

dit_slide:
    resource: "@AdminBundle/Resources/config/routing/slide.yml"
    prefix:   /slide